server:
  port: 80
spring:
  application:
    name: myteam-mall-zuul
  redis:
    host: 124.70.139.239
  session:
    store-type: redis
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    mall-portal:
      service-id: myteam-mall-portal
      path: /**
