server:
  port: 80
spring:
  application:
    name: myteam-mall-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    mall-portal:
      service-id: myteam-mall-portal
      path: /**
