server:
  port: 4000

spring:
  application:
    name: myteam-mall-portal
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka